Sirimangalo/meditation-plus-angular

- src/app/admin-guard.ts
- src/app/admin/admin.component.ts
- src/app/admin/admin.css
- src/app/admin/admin.html
- src/app/admin/index.ts
- src/app/app.component.ts
- src/app/app.html
- src/app/app.routes.ts
- src/app/user/user.service.ts
- src/platform/environment.ts
@olastor I've added an admin component. You could use it for the Testimonials review page.
> feat: Adds admin component

- src/app/admin/admin.html
- src/app/admin/commitment/commitment-admin.component.ts
- src/app/admin/commitment/commitment-admin.html
- src/app/admin/commitment/commitment-form.component.ts
- src/app/admin/commitment/commitment-form.html
- src/app/app.routes.ts
- src/app/commitment/commitment.service.ts
- src/app/commitment/index.ts
> feat: adds commitment administration

- src/app/appointment/appointment.component.ts
> feat(appointment): adds support for half hour appointments

- src/app/profile/profile-form.component.ts
- src/app/profile/profile-form.css
- src/app/profile/profile-form.html
> feat(profile): adds ability to change password

- src/app/app.component.ts
- src/app/emoji/emoji-select.component.css
- src/app/emoji/emoji-select.component.html
- src/app/emoji/emoji-select.component.ts
- src/app/emoji/emoji.pipe.spec.ts
- src/app/emoji/emoji.pipe.ts
- src/app/emoji/emojione-awesome.css
- src/app/emoji/index.ts
- src/app/message/message.component.ts
- src/app/message/message.css
- src/app/message/message.html
> feat: adds emoji support

- src/app/admin/appointment/appointment-form.html
- src/app/appointment/appointment.html
> fix(appointment): adds select for weekdays

- src/app/app.css
> Fixes Firefox scrollbar bug

- .gitignore
- src/app/app.routes.ts
- src/app/appointment/appointment.html
- src/app/commitment/commitment.component.ts
- src/app/help/help.html
- src/app/login/login.component.ts
- src/app/login/login.css
- src/app/login/login.html
- src/app/meditation/list-entry/list-entry.html
- src/app/message/message.html
- src/app/profile/profile-form.html
- src/app/profile/profile.component.ts
- src/app/profile/profile.html
- src/app/user/user.service.ts
> feat: deletes username and adds name

- .gitignore
- .travis.yml
- CHANGELOG.md
- config/webpack.prod.js
- src/app/app.routes.ts
- src/app/update/index.ts
- src/app/update/update.component.ts
- src/app/update/update.html
- src/main.browser.ts
> feat: adds update mechanism

- src/app/emoji/emoji-select.component.ts
- src/app/message/message.component.ts
- src/app/message/message.css
- src/app/message/message.html
> feat: add mark as question feature

- src/app/profile/profile-form.html
> fix: remove typo

- src/app/app.html
> feat: open guide in new tab

- src/app/meditation/meditation.component.ts
- src/app/profile/profile-form.component.ts
- src/app/profile/profile-form.html
Appearance is not perfectly great so far (because of select). But it should works. Would close #23
> feat: add alarm settings in profile

- src/app/message/message.component.ts
- src/app/message/message.css
- src/app/message/message.html
- src/app/message/message.service.ts
> Admin can unmark questions

- src/app/message/message.component.ts
- src/app/message/message.css
- src/app/message/message.html
> feat: add button show only questions in chat

- src/app/home/home.component.ts
- src/app/meditation/meditation.component.ts
- src/app/meditation/meditation.html
Used localStorage, because It would work offline.
Closes #96
> feat(meditation): saves and reads last session from localStorage

- src/app/meditation/meditation.component.ts
- src/app/meditation/meditation.css
- src/app/meditation/meditation.html
> feat(meditation): switch to barchart + highlight cur. hour

- src/app/meditation/meditation.component.ts
> fix: play sound on phones

- src/app/app.routes.ts
- src/app/appointment/appointment.component.ts
- src/app/appointment/appointment.css
- src/app/appointment/appointment.html
- src/app/appointment/appointment.service.ts
> Admin can remove users from appointments

- src/app/admin/admin.html
- src/app/admin/testimonial/testimonial-admin.component.ts
- src/app/admin/testimonial/testimonial-admin.css
- src/app/admin/testimonial/testimonial-admin.html
- src/app/app.html
- src/app/app.routes.ts
- src/app/testimonial/testimonial.service.ts
Equals `feat/testimonials-admin`, but only 1 commit. Ref: #13
> Add testimonials admin page

- src/app/meditation/list-entry/list-entry.component.ts
- src/app/meditation/list-entry/list-entry.css
- src/app/meditation/list-entry/list-entry.html
> feat(meditation): adds better ui feedback for like button

- src/app/app.component.ts
- src/app/app.spec.ts
- src/app/meditation/meditation.component.ts
- src/platform/environment.ts
> feat: adds current meditation state to title

- src/app/meditation/chart/meditation-chart.component.ts
- src/app/meditation/chart/meditation-chart.css
- src/app/meditation/chart/meditation-chart.html
- src/app/meditation/meditation.component.ts
- src/app/meditation/meditation.css
- src/app/meditation/meditation.html
Only merge (and review) after #120 has been merged.
> Checks minute change more accurately

- src/app/profile/profile.component.ts
- src/app/profile/profile.css
- src/app/profile/profile.html
> feat(profile): adds basic stats

- src/app/appointment/appointment.html
Depends on https://github.com/Sirimangalo/meditation-plus-server/pull/23.
Closes #70
> feat(appointment): allows for directly changing appointment

- src/app/appointment/appointment.component.ts
- src/app/appointment/appointment.css
- src/app/appointment/appointment.html
> feat(appointment): adds list view

- src/app/meditation/list-entry/list-entry.css
- src/app/meditation/list-entry/list-entry.html
- src/app/message/message.css
- src/app/message/message.html
> feat(meditation,message): makes usernames clickable

- src/app/app.html
- src/app/app.routes.ts
- src/app/live/index.ts
- src/app/live/live.component.ts
- src/app/live/live.html
- src/app/live/live.service.ts
- src/platform/environment.ts
> feat: adds live stream component

- src/app/home/home.component.ts
- src/app/home/home.css
- src/app/home/home.html
- src/app/user/user-form.component.html
Needs to be rebased on master, after #147 is merged.
Closes #83
> feat: adds tabless layout

- src/app/message/message.css
- src/app/message/message.html
With the new tab routes the `href="#"` reloads the page
> repair emoji select

- src/app/testimonial/testimonial.css
Testimonials textarea's width was to big
> Small CSS change

- src/app/help/help.css
- src/app/help/help.html
CSS from https://github.com/klarsys/angular-material-icons/issues/15
> fix: lower emoji-select icon and make it inline

- src/app/profile/profile.component.ts
- src/app/profile/profile.html
- src/app/user/user-form.component.html
Depends on https://github.com/Sirimangalo/meditation-plus-server/pull/27 
Fixes #170
> feat(profile): adds ability to hide stats

- src/app/message/message.css
- src/app/message/message.html
- src/app/online/online.component.css
- src/app/online/online.component.html
> Mark meditators

- src/app/profile/profile.component.ts
- src/app/profile/profile.html
> feat(profile): adds duration pipe to stats

- src/app/message/message.component.ts
Waiting for confirmation of @yuttadhammo.
> feat(message): adds hint when posting a question without Q:

- src/app/message/list-entry/message-list-entry.component.css
- src/app/message/list-entry/message-list-entry.component.html
- src/app/message/list-entry/message-list-entry.component.ts
- src/app/message/message.component.ts
- src/app/message/message.css
- src/app/message/message.html
> feat(message): refactor + better UI feedback for answering

- src/app/help/help.component.ts
- src/app/help/help.css
- src/app/help/help.html
> feat(help): adds explanation of the badge system

- package.json
https://github.com/dzonatan/angular2-linky/issues/5
Fixes karma errors.
> chore(package.json): updates angular2-linky

- src/app/meditation/meditation.css
- src/app/meditation/meditation.html
> feat(meditation): adds two progress circles

- src/app/home/home.component.ts
- src/app/home/home.html
- src/app/user/user-form.component.html
See also: https://github.com/Sirimangalo/meditation-plus-server/pull/36
closes #220, closes #219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sirimangalo/meditation-plus-angular/238)
> fix: remove tabless layout

- src/app/home/home.component.ts
- src/app/home/home.css
- src/app/home/home.html
- src/app/meditation/meditation.component.ts
Closes #207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sirimangalo/meditation-plus-angular/239)
> feat: disable chat & questions during meditation

- src/app/meditation/list-entry/list-entry.component.ts
- src/app/meditation/list-entry/list-entry.css
- src/app/meditation/list-entry/list-entry.html
- src/app/meditation/meditation.component.ts
- src/app/meditation/meditation.css
- src/app/meditation/meditation.html
- src/app/meditation/meditation.service.ts
Depends on https://github.com/Sirimangalo/meditation-plus-server/pull/33
Closes #206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sirimangalo/meditation-plus-angular/228)
> feat: adds "like all"

- src/app/app.component.ts
- src/app/home/home.component.ts
- src/app/home/home.html
Fixes misbehaviour of Sidenav when returning to Home on Chrome in Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sirimangalo/meditation-plus-angular/237)
> fix(Home): prevent Sidenav from opening without interaction

- src/app/meditation/meditation.component.ts
> fix: reactivate tabs after meditation end

- src/app/app.html
- src/app/home/home.html
- src/app/message/message.component.ts
- src/app/message/message.html
@olastor feel free to review after it has been merged.
Fixes #249 fixes #245 fixes #243
> chore: removes gestures and optimizes scrolling

- src/main.browser.ts
Kind of hacky, but I haven't found a better way.
Closes #248
> feat(main.browser): adds information about app update

- src/app/app.component.css
- src/app/meditation/meditation.component.css
- src/app/meditation/meditation.component.html
- src/app/question/question.component.css
- src/app/question/question.component.html
- src/app/testimonial/testimonial.component.css
**Do not merge:** Introduced layout bugs for safari. We need to debug this. I don't have enough experience with flexbox.
Fixes #246
> fix: fixes firefox layout problems with flexbox

- src/app/meditation/chart/meditation-chart.component.ts
- src/app/profile/profile.component.html
- src/app/profile/profile.component.ts
Haven't tested this one. But is same code as old PR
> fix: don't label duration as 'days'

- src/app/question/list-entry/question-list-entry.component.html
- src/app/question/question.css
- src/app/question/question.html
- src/main.browser.ts
Closes #256 
@yuttadhammo @binarious Are these fine? Any changes or additional rules needed?
> feat: add rules to ask tab

- src/app/meditation/meditation.component.html
> feat(meditation): displays two separate countdowns

- src/app/live/live.component.css
- src/app/live/live.component.html
- src/app/meditation/meditation.component.html
- src/app/question/list-entry/question-list-entry.component.css
- src/app/question/list-entry/question-list-entry.component.html
Depends on https://github.com/Sirimangalo/meditation-plus-server/pull/45
Closes #198
> feat: adds YouTube integration for live page and questions

- src/app/message/list-entry/message-list-entry.component.css
- src/app/message/list-entry/message-list-entry.component.html
- src/app/message/list-entry/message-list-entry.component.ts
- src/app/message/message.component.html
- src/app/message/message.component.ts
- src/app/message/message.service.ts
- src/app/message/message.ts
- src/app/shared/longpress-button.directive.ts
- src/app/shared/shared.module.ts
Depends on https://github.com/Sirimangalo/meditation-plus-server/pull/44
Closes https://github.com/Sirimangalo/meditation-plus-angular/issues/90
> feat(message): adds ability to edit and delete messages

- src/app/profile/profile.component.html
> fix: display average meditation time as minutes

- src/app/message/list-entry/message-list-entry.component.css
- src/app/message/list-entry/message-list-entry.component.html
- src/app/online/online.component.css
- src/app/online/online.component.html
- src/app/profile/meditated-recently.directive.ts
- src/app/profile/profile.module.ts
- src/app/question/list-entry/question-list-entry.component.css
- src/app/question/list-entry/question-list-entry.component.html
Depends on https://github.com/Sirimangalo/meditation-plus-server/pull/47
Closes #279
> refactor: adds calculation of recently meditation to own directive

- src/app/admin/admin-index.component.html
- src/app/admin/admin.module.ts
- src/app/admin/broadcast/broadcast-admin.component.ts
- src/app/admin/broadcast/broadcast-admin.css
- src/app/admin/broadcast/broadcast-admin.html
- src/app/admin/broadcast/broadcast-form.component.ts
- src/app/admin/broadcast/broadcast-form.html
- src/app/admin/broadcast/broadcast.service.ts
- src/app/app.routes.ts
- src/app/question/list-entry/question-list-entry.component.css
- src/app/question/list-entry/question-list-entry.component.html
- src/app/question/list-entry/question-list-entry.component.ts
- src/app/question/question.service.ts
Depends on https://github.com/Sirimangalo/meditation-plus-server/pull/48
Closes #277 
Please check in detail.
> feat: adds broadcast and answering mode

- src/app/question/list-entry/question-list-entry.component.html
> fix: remove thumb up if no likes

- src/app/help/help.component.html
Removes Github Logo, links to issues and adds a button to submit an issue.
> feat: add button to issues page

- src/app/question/list-entry/question-list-entry.component.html
> fix(question): add check for deleted user

- src/app/profile/profile.component.css
- src/app/profile/profile.component.html
- src/app/profile/profile.component.ts
> feat(profile): add edit and delete links for admin

- src/app/login/login.component.ts
- src/app/meditation/chart/meditation-chart.component.ts
- src/app/meditation/meditation.component.ts
- src/app/user/user-form.component.html
Depends on https://github.com/Sirimangalo/meditation-plus-server/pull/58
Closes #306
> feat: add account suspension

- src/app/meditation/meditation.component.css
- src/app/meditation/meditation.component.html
> fix: prevent circle value from being 0

- src/app/question/question.component.ts
> fix(question): reload answered questions on websocket event

- src/app/help/help.component.html
- src/app/meditation/meditation.component.html
- src/app/meditation/meditation.component.ts
- refactor bell timer
- add static sounds
> fix: continue bell on page reload

- src/app/profile/badge/badge.component.html
fixes #324 
Edit: Tested successfully
> feat: show badges in reversed order

- src/app/meditation/meditation.component.ts
> feat: update commitment after meditation

- src/app/appointment/appointment.component.ts
> feat: add confirm dialog for appointments

- src/app/meditation/meditation.component.html
> feat: increase maximum time of walking/sitting to 240

- src/app/user/user-form.component.html
depends on https://github.com/Sirimangalo/meditation-plus-server/pull/135
closes #192
> feat: add subscribeTestimonials option to user form

- src/app/login/login.component.ts
> fix: make trigger string more accurate

- src/app/message/message.component.ts
fix for bug causing error on empty chat
> fix: lastMessage is undefined on first 2 messages

- src/app/home/home.component.ts
- src/push-service.js
depends on https://github.com/Sirimangalo/meditation-plus-server/pull/138
> feat(push-service): add click event to notifications

- src/app/emoji/emoji.pipe.ts
- src/app/message/message.component.html
- src/app/message/message.component.ts
Easy fixes for https://github.com/Sirimangalo/meditation-plus-angular/issues/420.
> chore: add simple perf optimizations

- src/app/message/list-entry/message-list-entry.component.html
- src/app/message/mentions.pipe.ts
- src/app/message/message.component.ts
- src/app/message/message.module.ts
- src/app/user/user.service.ts
depends on https://github.com/Sirimangalo/meditation-plus-server/pull/139
closes #58
> feat(message): add tab completion and mentions

- CHANGELOG.md
> docs(changelog): update to version 1.10.0

- src/app/message/message.component.ts
> fix(message): update lastMessage for chat indicator

- src/app/home/home.component.html
- src/app/home/home.component.styl
- src/app/home/home.component.ts
- src/app/message/message.service.ts
- src/app/question/question.service.ts
depends on https://github.com/Sirimangalo/meditation-plus-server/pull/144
Adds count of open questions into 'ask' tab and improves requesting count of new messages by only getting the count, not all messages.
> feat: add ask indicator

- src/app/admin/testimonial/testimonial-admin.html
- src/app/testimonial/testimonial.component.html
> fix(testimonial): support deleted users

- src/app/login/login.component.html
closes #479
spell checking please :smile:
> feat(login): add link to troubleshooting page

- src/app/question/list-entry/question-list-entry.component.html
> fix(question): show date 'answeredAt' not 'answeringAt' in quesiton list-entry

- src/app/question/question.component.html
> feat(ask): move 'Please ...' toggled submit form & move emoji select next to textarea

- src/app/user/user-form.component.html
- src/app/user/user-form.component.styl
> feat(user-form): add styling to admin section

- src/app/profile/offline-meditation/offline-meditation.component.ts
- src/app/profile/offline-meditation/offline-meditation.html
> fix(offline-meditation): improve styling of datepicker and time input

- src/app/user/user-form.component.html
closes #504 together with  https://github.com/Sirimangalo/meditation-plus-server/pull/154
> feat: add option for notify on schedule changes

- src/app/login/login.component.ts
> fix(login): reset form after signup

- src/app/user/testing/fake-user.service.ts
fixes failing of tests of current build
> fix(user-service): add missing test function 'getUserId()'

- src/index.html
> fix(index.html): add missing font reference

- .travis.yml
> fix(travis): allow tests for forked repos

- src/app/admin/appointment/appointment-admin.component.ts
- src/app/admin/appointment/appointment-form.component.ts
- src/app/appointment/appointment.component.ts
- src/app/appointment/appointment.service.ts
- src/app/appointment/testing/fake-appointment.service.ts
- src/app/environment.ts
- src/app/shared/index.ts
- src/app/shared/settings.service.ts
- src/app/shared/testing/fake-settings.service.ts
- src/app/user/user-form.component.html
> refactor(appointments): move processing of increment to server 

- src/app/meditation/meditation.component.ts
> refactor(meditation): refactor bell + add support for new sound files in AAC

- src/app/admin/appointment/appointment-admin.component.html
- src/app/admin/appointment/appointment-admin.component.ts
- src/app/user/user-form.component.html
- src/app/user/user-form.component.spec.ts
- src/app/user/user-form.component.ts
for https://github.com/Sirimangalo/meditation-plus-server/pull/167
highly untested. Cannot test locally because no push support..
> refactor(appointment): move option for notifications to user form

- src/app/admin/appointment/appointment-admin.component.html
- src/app/admin/appointment/appointment-admin.component.ts
- src/app/app.component.styl
- src/app/appointment/appointment.component.html
- src/app/appointment/appointment.component.spec.ts
- src/app/appointment/appointment.component.ts
closes #515 
backend: https://github.com/Sirimangalo/meditation-plus-server/pull/168
> feat(appointment): add interface for changing the timezone for all appointments 

- src/app/meditation/meditation.component.ts
> fix(meditation): fix loading of audio bell

- src/app/appointment/appointment.component.html
- src/app/appointment/appointment.component.styl
> feat: Automatically choose list/tab view based on window size

- src/app/admin/appointment/appointment-admin.component.html
- src/app/admin/appointment/appointment-admin.component.styl
- src/app/admin/appointment/appointment-admin.component.ts
- src/app/admin/appointment/appointment-form.component.html
- src/app/admin/appointment/appointment-form.component.ts
- src/app/appointment/appointment.component.html
- src/app/appointment/appointment.component.ts
- src/app/appointment/appointment.service.ts
- src/app/appointment/appointment.ts
- src/app/appointment/hour.pipe.ts
depends on https://github.com/Sirimangalo/meditation-plus-server/pull/186
- Categorizes appointments by their hour
- Adds checkboxes for each day of week for easy adding/removing of appointments with the same hour
- gets rid of appointments increment
> refactor(appointment-admin): New interface for easier management of appointments
